### PR TITLE
Made some updates...

### PR DESCRIPTION
**Pull request by davemcg3**
## Intro
First, let me say, I love this idea. Super fun and snarky. Thanks for making it open source so it could come in front of me! I hope you like the changes here.

## Changes
1. Rewrote the JavaScript (still vanilla) to use modules for a little more of an object-oriented approach, also makes it easier to extend (IMO). 
2. Started with just wanting to make the number of attendees and the hourly wage changeable during a meeting (in case execs were called in partway through) which I accomplished by breaking the meeting into increments and then looking back over the increments to get the details needed to display. Then I kept adding things, because meetings are boring and this was interesting. 
3. Connected to localStorage to store the past 10 meetings. 
4. When I was displaying those I realized I wanted to be able to set a meeting purpose, so added that. 
5. Added a reset button. Covered most of the TODOs I saw (except the one about 1977, not sure where to get that info). 
6. Reworked the bootstrap a little bit to allow for a little more of a dynamic experience, and a significantly better experience on mobile. 

## Concluding thoughts
Probably wouldn't pass lint or a build process, so maybe that's an improvement that could be made, but that doesn't seem to be setup on this project. Also there are no tests, so that should probably be added at some point. Looking at the source on the website it looks like you have a build process that's not encapsulated in the repo, so I'd love some insight into that.

Per requirements, changes made while in meetings.

### CODE REVIEW

**Comment by chaserx** [comment]
@davemcg3 

First, let me say I am **very sorry** that I am just now seeing your contribution. 🙏 I have let this and some other projects completely fall off my radar. I work at GitLab, and, as such, I don't get back here as much as I should to support these older projects. 

Second, thank you for the contribution! 🕺 I think it makes some nice looking enhancements and refinements, and you certainly, get the spirit of the project `Per requirements, changes made while in meetings.` 🙂

> Probably wouldn't pass lint or a build process, so maybe that's an improvement that could be made, but that doesn't seem to be setup on this project. Also there are no tests, so that should probably be added at some point.

This was put together with haste. So, style enforcement and testing would good things to include. 

> Looking at the source on the website it looks like you have a build process that's not encapsulated in the repo, so I'd love some insight into that.

Yeah. Not so much a build process as just a "chuck it over the wall" deploy process. That was one of the advantages to using the vanilla script block javascript. Mostly just copying the contents of this directory into an S3 bucket that is then pushed to Cloudfront. Not sure that's the best, but again hasty web development. If improvements need some frontend tooling then maybe we can consider including some pragmatic options there. 

> Reworked the bootstrap a little bit to allow for a little more of a dynamic experience, and a significantly better experience on mobile.

I wonder if there's a compromise that works with large and small screens? On a larger monitor, I would prefer to have the background image fill vertically. 

Screen Shot 2022-11-02 at 15 34 16

**Comment by davemcg3** [comment]
No issue with the delay, I deployed my version to Github pages so it's been working just fine when I needed it! 😉 
I also didn't see your response for the last year and a half, heh. I did notice it on Friday, but it was after my last meeting so I had to wait until today to make the update! 🤣

I love that you made this repo public, was awesome to find it.

Easy change to make the background cover the whole screen, works on both desktop and mobile. 

If you wanted to add front-end tooling that could be done, but the project as it is probably makes it not necessary. Regardless, it should be done in a separate PR from this anyway. Same with testing. There are a lot of configurations to debate for each of those. 😬

**Comment by chaserx** [comment]
> No issue with the delay, I deployed my version to Github pages so it's been working just fine when I needed it! 😉
I also didn't see your response for the last year and a half, heh. I did notice it on Friday, but it was after my last meeting so I had to wait until today to make the update! 🤣

Thanks again for your contribution. 

I'm going to approve and merge your pull request now.

**Comment by chaserx** [comment]
@davemcg3 Thanks again! Looks great!

I merged your PR and deployed the latest master.

Screenshot 2024-06-10 at 1 38 14 PM

**Pull request merged**
